### ISSUE TITLE
Typo RTSP -> RTPS

### ISSUE THREAD

**Issue by joonas-fi** [tiiuae/fogsw_systemd#24]
https://github.com/tiiuae/fogsw_systemd/blob/bbf96ed046bb02f9fc18110fc3e9ff3d1c0e0bd9/system/agent_protocol_splitter.service#L2

The fact that RTSP is also a protocol makes the typo more confusing :)

**Comment by maseabunikie** [comment]
Should be soon fixed in the PR https://github.com/tiiuae/fogsw_systemd/pull/36 .
